{% set version = "5.212" %}

package:
  name: qtwebkit
  version: {{ version }}

source:
  url: http://download.qt.io/snapshots/ci/qtwebkit/{{ version }}/latest/src/submodules/qtwebkit-opensource-src-{{ version }}.tar.xz
  sha256: 10cbdaba60aac79d27016aa05bae9ab3ec7b0aed4df163debfbf8fddd66adc14
  patches:
    # include is wrong for older OSX version
    #- 0001-osx-fix-vm-include.patch  # [osx]
    # Crypto functions aren't available under older OSX. Use /dev/urandom instead
    # like Linux (hope this is ok)
    #- 0002-osx-fix-urandom.patch  # [osx]
    # Fix path for ICU libs on Windows - seems to pick up some system libs instead
    - 0003-win-fix-icu-path.patch  # [win]
    # QOS Stuff introduced in OSX SDK 10.10
    #- 0004-osx-noqos.patch  # [osx]
    # MSYS gperf needs Unix newlines
    - 0005-win-gperf-lf.patch  # [win]

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # The CDT packages below are those used in qt-feedstock
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]    
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libselinux') }}            # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxcb') }}                # [linux]
    - {{ cdt('libxext') }}               # [linux]
    - {{ cdt('libxau') }}                # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - cmake
    - ninja
    # On Linux, cmake picks up /usr/bin/python2 (since python2 is checked
    # first) which is v2.6 and too old. Workaround this by giving it a
    # new Python 2
    - python 2.7  # [linux]
    # On other platforms, use a recent Python (but fix version so we don't
    # end up with combos being built). This is especially needed on Windows
    # so we end up with a Python with a recent runtime. 
    - python 3.8  # [not linux]
    # Need Unix line endings on Windows with output of perl scripts
    - perl  # [not win]
    - m2-perl  # [win]
    # only ruby 2.7 and later appear to be available on Windows
    # and leaving this blank ends up with all possible combination
    # of versions...
    - ruby 2.7 
    - m2-bison  # [win]
    - bison  # [unix]
    - m2-flex  # [win]
    - flex  # [unix]
    - m2-gperf  # [win]
    - gperf  # [unix]
  host:
    - qt
    - libxslt
    - libxml2
    - sqlite
    - jpeg
    - zlib
    - libpng
    - libwebp
    - icu
  run:
    - qt
    - libxslt
    - libxml2
    - sqlite
    - jpeg
    - zlib
    - libpng
    - libwebp
    - icu

test:
  commands:
    - test -f $PREFIX/lib/libQt5WebKit${SHLIB_EXT}  # [not win]
    - test -f $PREFIX/lib/libQt5WebKitWidgets${SHLIB_EXT}  # [not win]
    - if not exist %LIBRARY_BIN%\\Qt5WebKit.dll exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\Qt5WebKitWidgets.dll exit 1  # [win]

about:
  home: https://wiki.qt.io/Qt_WebKit
  license: LGPL-2.1-only
  license_file: LICENSE.LGPLv21
  summary: 'WebKit is one of the major engine to render webpages and execute JavaScript code'
  description: |
    Qt WebKit is the port of WebKit on top of Qt. QtWebKit relies on the public APIs of Qt
    and can theoretically be used on any platform supported by Qt
    (theoretically because WebKit also requires a recent/good compiler).

extra:
  recipe-maintainers:
    - gillins
    - ceholden
    - ocefpaf
