{% set version = "5.6.2" %}
{% set ver = '.'.join(version.split('.')[:2]) %}

package:
  name: qtwebkit
  version: {{ version }}

source:
  url: http://download.qt.io/community_releases/{{ ver }}/{{ version }}/qtwebkit-opensource-src-{{ version }}.tar.xz
  sha256: 528a6b8b1c5095367b26e8ce4f3a46bb739e2e9913ff4dfc6ef58a04fcd73966

build:
  number: 1002
  skip: True  # [not osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    # qtwebkit needs to be used against the same version of Qt that
    # it was released for.
    - qt  {{ version }}
  run:
    - qt  {{ version }}

test:
  commands:
    - test -f $PREFIX/lib/libQt5WebKit.dylib  # [osx]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://wiki.qt.io/Qt_WebKit
  license: GPL-3.0
  license_file: LICENSE.GPLv3
  summary: 'WebKit is one of the major engine to render webpages and execute JavaScript code'
  description: |
    Qt WebKit is the port of WebKit on top of Qt. QtWebKit relies on the public APIs of Qt
    and can theoretically be used on any platform supported by Qt
    (theoretically because WebKit also requires a recent/good compiler).

extra:
  recipe-maintainers:
    - gillins
    - ceholden
    - ocefpaf
