{% set version = "5.7.1" %}
{% set ver = '.'.join(version.split('.')[:2]) %}

package:
  name: qtwebkit
  version: {{ version }}

source:
  url: http://download.qt.io/community_releases/{{ ver }}/{{ version }}/qtwebkit-opensource-src-{{ version }}.tar.xz
  sha256: a46cf7c89339645f94a5777e8ae5baccf75c5fc87ab52c9dafc25da3327b5f03

build:
  number: 0
  skip: True  # [not osx]

requirements:
  build:
    - toolchain
    # qtwebkit needs to be used against the same version of Qt that
    # it was released for.
    - qt {{ version }}
  run:
    - qt {{ version }}

test:
  commands:
    - test -f $PREFIX/lib/libQt5WebKit.dylib  # [osx]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://wiki.qt.io/Qt_WebKit
  license: GPL-3.0
  license_file: LICENSE.GPLv3
  summary: 'WebKit is one of the major engine to render webpages and execute JavaScript code'
  description: |
    Qt WebKit is the port of WebKit on top of Qt. QtWebKit relies on the public APIs of Qt 
    and can theoretically be used on any platform supported by Qt 
    (theoretically because WebKit also requires a recent/good compiler).

extra:
  recipe-maintainers:
    - gillins
    - ceholden
    - ocefpaf
