{% set version = "5.212" %}
{% set snapshotid = "1600955993" %}

package:
  name: qtwebkit
  version: {{ version }}

source:
  #url: http://download.qt.io/snapshots/ci/qtwebkit/{{ version }}/{{ snapshotid }}/src/submodules/qtwebkit-opensource-src-{{ version }}.tar.xz
  url: https://github.com/qtwebkit/qtwebkit/releases/download/qtwebkit-5.212.0-alpha4/qtwebkit-5.212.0-alpha4.tar.xz
  sha256: 9ca126da9273664dd23a3ccd0c9bebceb7bb534bddd743db31caf6a5a6d4a9e6
  patches:
    # Patches to make this (older) aplpha the same as the (later) snaphot
    # we were downloading from qt.io but was then removed
    - 0000-fixes-from-snapshot.patch
    # Fix path for ICU libs on Windows - seems to pick up some system libs instead
    - 0001-win-fix-icu-path.patch  # [win]
    # MSYS gperf needs Unix newlines
    - 0002-win-gperf-lf.patch  # [win]
    # Fix TRUE/FALSE definition for newer ICU
    - 0003-linux-icu-TRUE-FALSE.patch  # [linux]
    ## glib patch from https://github.com/archlinux/svntogit-packages/blob/packages/qt5-webkit/trunk/glib-2.68.patch
    - 0004-linux-glib.patch  # [linux] 
    # From webkit master
    - 0005-osx-arm64.patch  # [osx]

build:
  number: 16
  run_exports:
    - qtwebkit

requirements:
  build:
    - sysroot_linux-64 2.17  # [linux64]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # The CDT packages below are those used in qt-feedstock
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]    
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libselinux') }}            # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxcb') }}                # [linux]
    - {{ cdt('libxext') }}               # [linux]
    - {{ cdt('libxau') }}                # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - cmake
    - ninja
    # On Linux, cmake picks up /usr/bin/python2 (since python2 is checked
    # first) which is v2.6 and too old. Workaround this by giving it a
    # new Python 2
    - python 2.7  # [linux]
    # On other platforms, use a recent Python (but fix version so we don't
    # end up with combos being built). This is especially needed on Windows
    # so we end up with a Python with a recent runtime. 
    - python 3.8  # [not linux]
    - perl
    # only ruby 2.7 and later appear to be available on Windows
    # and leaving this blank ends up with all possible combination
    # of versions...
    - ruby 2.7 
    - m2-bison  # [win]
    - bison  # [unix]
    - m2-flex  # [win]
    - flex  # [unix]
    - m2-gperf  # [win]
    - gperf  # [unix]
  host:
    - qt-main
    - glib  # [linux]
    - libxslt
    - libxml2
    - sqlite
    - libjpeg-turbo
    - zlib
    - libpng
    - libwebp
    - icu
  run:
    - qt-main
    - glib
    - libxslt
    - libxml2
    - sqlite
    - libjpeg-turbo
    - zlib
    - libpng
    - libwebp
    - icu
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]
    
test:
  commands:
    - test -f $PREFIX/lib/libQt5WebKit${SHLIB_EXT}  # [not win]
    - test -f $PREFIX/lib/libQt5WebKitWidgets${SHLIB_EXT}  # [not win]
    - if not exist %LIBRARY_BIN%\\Qt5WebKit.dll exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\Qt5WebKitWidgets.dll exit 1  # [win]

about:
  home: https://wiki.qt.io/Qt_WebKit
  license: LGPL-2.1-only
  license_file: LICENSE.LGPLv21
  summary: 'WebKit is one of the major engine to render webpages and execute JavaScript code'
  description: |
    Qt WebKit is the port of WebKit on top of Qt. QtWebKit relies on the public APIs of Qt
    and can theoretically be used on any platform supported by Qt
    (theoretically because WebKit also requires a recent/good compiler).

extra:
  recipe-maintainers:
    - gillins
    - ceholden
    - ocefpaf
