{% set version = "5.212" %}
{% set snapshotid = "1600955993" %}

package:
  name: qtwebkit
  version: {{ version }}

source:
  #url: http://download.qt.io/snapshots/ci/qtwebkit/{{ version }}/{{ snapshotid }}/src/submodules/qtwebkit-opensource-src-{{ version }}.tar.xz
  url: https://github.com/qtwebkit/qtwebkit/releases/download/qtwebkit-5.212.0-alpha4/qtwebkit-5.212.0-alpha4.tar.xz
  sha256: 9ca126da9273664dd23a3ccd0c9bebceb7bb534bddd743db31caf6a5a6d4a9e6
  patches:
    # Patches to make this (older) aplpha the same as the (later) snaphot
    # we were downloading from qt.io but was then removed
    - 0000-fixes-from-snapshot.patch
    # Fix path for ICU libs on Windows - seems to pick up some system libs instead
    - 0001-win-fix-icu-path.patch  # [win]
    # MSYS gperf needs Unix newlines
    - 0002-win-gperf-lf.patch  # [win]
    # Fix TRUE/FALSE definition for newer ICU
    - 0003-linux-icu-TRUE-FALSE.patch  # [linux]
    ## glib patch from https://github.com/archlinux/svntogit-packages/blob/packages/qt5-webkit/trunk/glib-2.68.patch
    - 0004-linux-glib.patch  # [linux]
    # From webkit master
    - 0005-osx-arm64.patch  # [osx]
    # https://github.com/qtwebkit/qtwebkit/pull/1100
    - 0006-Fix-xmlError-for-libxml2-2.12.patch

    # Patches from hmaarrfk
    - 0007-Find-better-python.patch
    - 0008-Include-more-c-headers.patch
    # https://src.fedoraproject.org/rpms/qt5-qtwebkit/blob/rawhide/f/webkit-offlineasm-warnings-ruby27.patch
    # https://github.com/WebKit/WebKit/commit/c7d19a492d97f9282a546831beb918e03315f6ef
    # https://www.linuxquestions.org/questions/slackware-14/regression-on-current-with-qt5-webkit-4175720296/
    - 0009-Fixup-for-newer-ruby.patch
    - 0010-Don-t-double-define-things-for-CXX17-compilers.patch

build:
  number: 17
  run_exports:
    - qtwebkit

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    # The CDT packages below are those used in qt-feedstock
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libselinux') }}            # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxcb') }}                # [linux]
    - {{ cdt('libxext') }}               # [linux]
    - {{ cdt('libxau') }}                # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - cmake
    - ninja
    - python 3.12
    - perl
    - ruby >=3
    - bison  # [unix]
    - flex  # [unix]
    - gperf  # [unix]
    - m2-bison  # [win]
    - m2-flex  # [win]
    - m2-gperf  # [win]
  host:
    - qt-main
    - glib  # [linux]
    - libxslt
    - libxml2
    - sqlite
    - libjpeg-turbo
    - zlib
    - libpng
    - libwebp
    - icu

test:
  commands:
    - test -f $PREFIX/lib/libQt5WebKit${SHLIB_EXT}  # [not win]
    - test -f $PREFIX/lib/libQt5WebKitWidgets${SHLIB_EXT}  # [not win]
    - if not exist %LIBRARY_BIN%\\Qt5WebKit.dll exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\Qt5WebKitWidgets.dll exit 1  # [win]

about:
  home: https://wiki.qt.io/Qt_WebKit
  license: LGPL-2.1-only
  license_file: LICENSE.LGPLv21
  summary: 'WebKit is one of the major engine to render webpages and execute JavaScript code'
  description: |
    Qt WebKit is the port of WebKit on top of Qt. QtWebKit relies on the public APIs of Qt
    and can theoretically be used on any platform supported by Qt
    (theoretically because WebKit also requires a recent/good compiler).

extra:
  recipe-maintainers:
    - gillins
    - ceholden
    - ocefpaf
