{% set version = "5.9.0" %}
{% set ver = '.'.join(version.split('.')[:2]) %}

package:
  name: qtwebkit
  version: {{ version }}

source:
  url: http://download.qt.io/community_releases/{{ ver }}/{{ version }}-final/qtwebkit-opensource-src-{{ version }}.tar.xz
  sha256: 8dad193b740055a998312e04a040f2e32a923c0823b2d239b24eab08276a4e04

build:
  number: 1
  skip: True  # [not osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    # qtwebkit needs to be used against the same version of Qt that
    # it was released for.
    - qt {{ ver }}
  run:
    - qt {{ ver }}

test:
  commands:
    - test -f $PREFIX/lib/libQt5WebKit.dylib  # [osx]

about:
  home: https://wiki.qt.io/Qt_WebKit
  license: GPL-3.0
  license_file: LICENSE.GPLv3
  summary: 'WebKit is one of the major engine to render webpages and execute JavaScript code'
  description: |
    Qt WebKit is the port of WebKit on top of Qt. QtWebKit relies on the public APIs of Qt
    and can theoretically be used on any platform supported by Qt
    (theoretically because WebKit also requires a recent/good compiler).

extra:
  recipe-maintainers:
    - gillins
    - ceholden
    - ocefpaf
