appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {osx: circle}
travis:
  secure: {BINSTAR_TOKEN: Trchb/h43Z9k/P5yGDo90jIDNvvzX0Eb1K2euoR6TJOY1mBR6jfL2QnJX/GcgHtldp+0jk4VKZNhlg91N5/m03BbtXpaCjTegGJ/t3YL2MYrNoj9ckveBcLlqkt5UVDlnZN74ffexnkWmUoA7d0xAlSBQ3+9Ylq/bSWSe0Bl5GQe+EV3mjA27erDNBn4EYn1LyF5tEocqT1bTs9ja2vyKu9rqRhDo9gIY3fDKs8V6DPWk8xZPxlu+2WNZuEdU3J1XCKRYYpi7kOdyeQnkIMIR+1heIFajNOAtctsqHIETj1xtIu4rG2EBysz38Jl3mOu5/eUAAtRqst/qlr++z7aei9IyYDQ3JBI8pKaMR4ExJNOcJzsMBiNBVrTflGqgWal//cGjbc/We4pVjKVKZToagcQmXAZZR9OTNn4JI+Y1Zvew7AUFQmnGiaNULFBglTnZpwIYmuKH9jHJZd23YK/aWCbAKOmGcYIsgEP2DjbJCEDCiqFOPfYylwihhhriuH8BmwPi0EgXF7yQjhXvWWzySVxtxtIKjRrNiVD1+RdY0X/Vz6fOTiUmtOLUDVH76d8ixq997tn1VFEfW6Z4ZBhvo+Nh0WUvBO3MJUurcYwAO5h0CYnPvjEODSzmtTkanoQSzVYk018WoJHr7rnAFnO28Y6BI6gGolzQG3ouKKD/II=}
